### ISSUE TITLE
ERR_FR_MAX_BODY_LENGTH_EXCEEDED

### ISSUE THREAD

**Issue by franz-geiser** [igocreate/node-ovh-storage#11]
Trying to upload a big file with the putStream function i get the error:
"Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit".

Editing the function in this way (adding maxContentLength and maxBodyLength) solves the problem: 
    axios({
      method: 'PUT',
      url, headers,
      data: stream,
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
    })

**Comment by arnaudm** [comment]
Thanks, we will release a new version soon with these changes

**Comment by arnaudm** [comment]
Fixed issue in version 0.3.2
