### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by solisoft** [igocreate/node-ovh-storage#2]
Hi, I set my credentials properly (works fine on Cyberduck, but I still have 401 Unauthorized as response for 
storage.getToken(function(err) {
  console.log(err)
})

Any ideas?

**Comment by pvomhoff** [comment]
Hi solisoft,

did you check if you entered all credentials in the right place?
In Cyberduck the username is the tenant id + the access key key separated by a `:` .
So in the this library the `username` is the access key and the `password` is the secret key.
And of course the `tenantId` id the tenant id.

Can you check this again?

**Comment by solisoft** [comment]
I think it's because now OVH API need tenantName instead of tenantId

Here in the OVH documentation :
$ curl -X POST $OS_AUTH_URL/tokens -H "Content-Type: application/json" -d '{"auth": {"tenantName": "'$OS_TENANT_NAME'", "passwordCredentials": {"username": "'$OS_USERNAME'", "password": "'$OS_PASSWORD'"}}}' | python -mjson.tool

https://www.ovh.com/us/g1872.managing_tokens

**Comment by arnaudm** [comment]
Hi @solisoft,

The tenantId parameter works, no need to add a tenantName.

Make sure you do not include the "AUTH_" prefix in the tenantId param - the tenantId should be 32chars long.
Did you create the users via the OVH backoffice in the "Openstack" section?

Arnaud
